### ISSUE TITLE
Enemies come back to life on loading save

### ISSUE THREAD

**Issue by RuairiQuote** [VinditCo/QuoteIssues#12]
**Build Version:** 0.62
**Issue Description:**
If the player clears a room of Enemies, saves the game and then proceeds to load said save, causes the dead enemies to come back to life.

**Reproduction Rate:** 100%
**Repoduction Steps:**

1. Start any combat zone in the main campaign
2. Kill all Enemies
3. Save the game
4. Load save.

**Comment by VinditCo** [comment]
Again, save issue : fixed in latest build
