### ISSUE TITLE
Collected Book Graphic reappears on load.

### ISSUE THREAD

**Issue by RuairiQuote** [VinditCo/QuoteIssues#14]
**Build Version:** 0.62
**Issue Description:**
If the player collects a book in game, saves and loads the file. The Book Model will reappear in its old spot. Interaction is disabled and the collected book is still in inventory, purely visual issue.

**Reproduction Rate:** 100%
**Repoduction Steps:**

1. Start L1
2. Enter first cave
3. Collect book and save
4. load save.

**Comment by VinditCo** [comment]
Fixed this. Issue with the save init system. Fixed in latest push.
